services:
  backend:
    build:
      context: ./backend
    container_name: expensetracker_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - redis_network
      - db-network

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expensetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis_network
  
volumes:
  postgres-data:
  redis-data:

networks:
  redis_network:
    driver: bridge
  db-network:
    driver: bridge