set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $KEYCLOAK_DB_DATABASE;
    CREATE USER $KEYCLOAK_DB_USER WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_DATABASE TO $KEYCLOAK_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname $KEYCLOAK_DB_DATABASE <<-EOSQL
    GRANT ALL ON SCHEMA public TO $KEYCLOAK_DB_USER;
EOSQL